# Site settings
title: Winter Breaks
client:
  name: FatFace
  link: https://www.fatface.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Time to batten down the hatches; as winter approaches, it might feel like your prospects of escaping the house are limited. But there’s no need to bury yourself under your duvet; together with Fat Face, we’ve put together the UK’s finest winter staycations for the whole family. So whether your thing is a stylish city getaway or a revitalising escape to the coast, find your next staycation here and wrap up warm with a choice selection of looks from Fat Face. Time for your stylish staycation.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/fatface" # the subpath of your site, e.g. /blog/
img:     "/fatface/_assets/img"
css:     "/fatface/_assets/css"
js:      "/fatface/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed